---
###########BZ UPDATES#############

- name: Include bz vars
  include_vars: bz.yml

- name: Patch system with provided RedHat advisories for RHEL 7
  command: yum -y --bz={{ item }}
    --exclude={{exclude_pkgs|default(omit)}}
  args:
    warn: "False"
  when: item not in bz_do_not_patch and item | match(".*-.*") and ansible_distribution_major_version=="7"
  with_items:
    - "{{ bzlist }}"

- name: Patch system with provided RedHat advisories for RHEL 8
  command: yum -y --bz={{ item }}
    --exclude={{exclude_pkgs|default(omit)}}
  args:
    warn: "False"
  when: item not in bz_do_not_patch and item | match(".*-.*") and ansible_distribution_major_version=="8"
  with_items:
    - "{{ bzlist }}"
