---
###########ADV UPDATES#############

- name: Include advisory vars
  include_vars: adv.yml

- name: Patch system with provided RedHat advisories for RHEL 6
  command: yum -y --advisory={{ item }}
    --exclude={{exclude_pkgs|default(omit)}}
  args:
    warn: "False"
  when: item not in adv_do_not_patch and item | match(".*-.*") and ansible_distribution_major_version=="6"
  with_items:
    - "{{ advlist }}"

- name: Patch system with provided RedHat advisories for RHEL 7
  command: yum -y --advisory={{ item }}
    --exclude={{exclude_pkgs|default(omit)}}
  args:
    warn: "False"
  when: item not in adv_do_not_patch and item | match(".*-.*") and ansible_distribution_major_version=="7"
  with_items:
    - "{{ advlist }}"

- name: Patch system with provided RedHat advisories for RHEL 8
  command: yum -y --advisory={{ item }}
    --exclude={{exclude_pkgs|default(omit)}}
  args:
    warn: "False"
  when: item not in adv_do_not_patch and item | match(".*-.*") and ansible_distribution_major_version=="8"
  with_items:
    - "{{ advlist }}"