---
###########STANDARD UPDATES: ALL PACKAGES#############

- name: Include OS specific variables
  include_vars: "rhel{{ ansible_distribution_major_version }}.yml"

- name: Patch x86_64 systems with optional repo enabled
  command: yum -y update
    --exclude={{exclude_pkgs|default(omit)}}
    --disablerepo="*"
    --enablerepo={{ enabled_repos }} {{ include_pkgs }}
  args:
    warn: "False"
  when:
    - ansible_architecture == "x86_64"
