---
- name: Patch All systems - BaseOS and AppStream repository enabled
  command: yum -y update
    --exclude={{ exclude_pkgs|default(omit) }}
    --enablerepo=rhel-{{ ansible_distribution_major_version }}-for-x86_64-baseos-rpms,rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms
  args:
    warn: "False"
  when:
    - ansible_architecture == "x86_64"

# - name: Patch DataBases on applicable x86_64 systems
#   command: yum -y update
#     --exclude={{ exclude_pkgs|default(omit) }}
#     --disablerepo=*
#     --enablerepo=MY_SQL_REPO_HERE
#   args:
#     warn: "False"
#   when:
#     - "'dbservers' in group_names"
#     - ansible_distribution_major_version == "8"
