---
enabled_repos: "rhel-6-server-optional-rpms,rhel-6-server-satellite-tools-6.2-rpms,Default_Organization_epel-x86_64-server-6_epel-x86_64-server-6,rhel-6-server-rpms,rhel-6-server-thirdparty-oracle-java-rpms"

