---
- name: Remove apache welcome.conf
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent
  become: true
  ignore_errors: true

- name: Reboot systems
  shell: sync && sleep 2 && shutdown -r now "Rebooting after patching job"
  changed_when:
    - "True"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to come back
  # local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=60
  local_action:
    wait_for host: {{ inventory_hostname }}
    port: 22
    state: started
    delay: 60
  become: false
  ignore_errors: true
  register: status

# - name: Wait for ports to come back up - MySQL
#   wait_for: state=started port={{ service_port|default(3306) }} timeout=300 connect_timeout=2 delay=10
#   become: false
#   ignore_errors: true
#   when:
#    -  "'allmysql' in group_names"

- name: Wait for ports to come back up - SSH
  # wait_for: state=started port={{ service_port|default(22) }} timeout=300 connect_timeout=2 delay=10
  wait_for:
    state: started
    port: "{{ service_port|default(22) }}"
    timeout: 300
    connect_timeout: 2
    delay: 10
  become: false
  ignore_errors: true
  when: status|succeeded
  

