---
- hosts: dbservers
  name: Reboot dbserver
  gather_facts: false
  become: yes
  serial: 1
  roles:
    - { reboot_systems ,  tags: [ 'reboot_mysql' ] }

- hosts: all:!dbservers
  name: Reboot all servers - NO dbservers
  gather_facts: false
  become: yes
  serial: 10
  roles:
    - { reboot_systems, tags: [ 'reboot_no_dbs' ] }
